server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  info:
    name: "Task Manager"
    version: "2.0.0"
    contact:
      name: "Sergey Rezchikov"
      email: "rezchikov.sa@phystech.edu"
  storage:
    directories:
      task-attachments: "upload"