server:
  port: 8080

spring:
  profiles:
    active: dev

app:
  name: "Task Manager"
  version: "2.0.0"

  session:
    attributes:
      favorite-tasks: "favoriteTasksIds"

  cookie:
    view-mode:
      name: "viewPreference"
      max-age: 604800 # 7 days

  storage:
    directories:
      task-attachments: "upload"